# Generated by Django 2.2.16 on 2020-11-12 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='班号')),
                ('subject', models.SmallIntegerField(choices=[(0, '大数据'), (1, 'Python'), (2, 'HTML')], verbose_name='所属学科')),
            ],
            options={
                'verbose_name': '班级信息',
                'verbose_name_plural': '班级信息',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='教师名称')),
            ],
            options={
                'verbose_name': '讲师信息',
                'verbose_name_plural': '讲师信息',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='学生名称')),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backs.Classroom', verbose_name='所属班级')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='课程名称')),
                ('description', models.TextField(max_length=120, verbose_name='课程描述')),
                ('teacher', models.ManyToManyField(to='backs.Teacher', verbose_name='讲师')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.SmallIntegerField(choices=[(0, '周一'), (1, '周二'), (2, '周三'), (3, '周四'), (4, '周五'), (5, '周六'), (6, '周七')], verbose_name='日期')),
                ('time', models.SmallIntegerField(choices=[(0, '上午'), (1, '下午')], verbose_name='时间段')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backs.Course', verbose_name='课堂名称')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backs.Classroom', verbose_name='班号')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backs.Teacher', verbose_name='讲师')),
            ],
            options={
                'verbose_name': '课程表信息',
                'verbose_name_plural': '课程表信息',
            },
        ),
    ]
