# Generated by Django 2.2.16 on 2020-11-12 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backs.Classroom', verbose_name='所属班级'),
        ),
    ]
